export const  ALL_CATEGORIES_REQUEST =  'ALL_CATEGORIES_REQUEST'
export const  ALL_CATEGORIES_SUCCESS =  'ALL_CATEGORIES_SUCCESS'
export const  ALL_CATEGORIES_FAILED =  'ALL_CATEGORIES_FAILED'


export const  NEW_CATEGORIES_REQUEST =  'NEW_CATEGORIES_REQUEST'
export const  NEW_CATEGORIES_SUCCESS =  'NEW_CATEGORIES_SUCCESS'
export const  NEW_CATEGORIES_FAILED =  'NEW_CATEGORIES_FAILED'
export const  NEW_CATEGORIES_RESET=  'NEW_CATEGORIES_RESET'

export const  DELETE_CATEGORIES_REQUEST =  'DELETE_CATEGORIES_REQUEST'
export const  DELETE_CATEGORIES_SUCCESS =  'DELETE_CATEGORIES_SUCCESS'
export const  DELETE_CATEGORIES_FAILED =  'DELETE_CATEGORIES_FAILED'
export const  DELETE_CATEGORIES_RESET=  'DELETE_CATEGORIES_RESET'

export const  UPDATE_CATEGORIES_REQUEST =  'UPDATE_CATEGORIES_REQUEST'
export const  UPDATE_CATEGORIES_SUCCESS =  'UPDATE_CATEGORIES_SUCCESS'
export const  UPDATE_CATEGORIES_FAILED =  'UPDATE_CATEGORIES_FAILED'
export const  UPDATE_CATEGORIES_RESET=  'UPDATE_CATEGORIES_RESET'

export const  ALL_CATEGORIES_DETAILS_REQUEST =  'ALL_CATEGORIES_DETAILS_REQUEST'
export const  ALL_CATEGORIES_DETAILS_SUCCESS =  'ALL_CATEGORIES_DETAILS_SUCCESS'
export const  ALL_CATEGORIES_DETAILS_FAILED =  'ALL_CATEGORIES_DETAILS_FAILED' 
export const  CLEAR_ERRORS =  'CLEAR_ERRORS'
