export const  ALL_PRODUCTS_REQUEST =  'ALL_PRODUCTS_REQUEST'
export const  ALL_PRODUCTS_SUCCESS =  'ALL_PRODUCTS_SUCCESS'
export const  ALL_PRODUCTS_FAILED =  'ALL_PRODUCTS_FAILED'

export const  CLEAR_ERRORS =  'CLEAR_ERRORS'

export const  DELETE_PRODUCTS_REQUEST =  'DELETE_PRODUCTS_REQUEST'
export const  DELETE_PRODUCTS_SUCCESS =  'DELETE_PRODUCTS_SUCCESS'
export const  DELETE_PRODUCTS_FAILED =  'DELETE_PRODUCTS_FAILED'
export const  DELETE_PRODUCTS_RESET=  'DELETE_PRODUCTS_RESET'


export const  ALL_PRODUCTS_DETAILS_REQUEST =  'ALL_PRODUCTS_DETAILS_REQUEST'
export const  ALL_PRODUCTS_DETAILS_SUCCESS =  'ALL_PRODUCTS_DETAILS_SUCCESS'
export const  ALL_PRODUCTS_DETAILS_FAILED =  'ALL_PRODUCTS_DETAILS_FAILED' 


export const  NEW_PRODUCTS_REQUEST =  'NEW_PRODUCTS_REQUEST'
export const  NEW_PRODUCTS_SUCCESS =  'NEW_PRODUCTS_SUCCESS'
export const  NEW_PRODUCTS_FAILED =  'NEW_PRODUCTS_FAILED'
export const  NEW_PRODUCTS_RESET=  'NEW_PRODUCTS_RESET'




export const  UPDATE_PRODUCTS_REQUEST =  'UPDATE_PRODUCTS_REQUEST'
export const  UPDATE_PRODUCTS_SUCCESS =  'UPDATE_PRODUCTS_SUCCESS'
export const  UPDATE_PRODUCTS_FAILED =  'UPDATE_PRODUCTS_FAILED'
export const  UPDATE_PRODUCTS_RESET=  'UPDATE_PRODUCTS_RESET'